; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri May 15 2020 11:07:38 GMT+0200 (heure d’été d’Europe centrale)
G1 S1 U-100 F10000 
G1 U12 F10000
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation








