; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri May 15 2020 11:07:39 GMT+0200 (heure d’été d’Europe centrale)

