; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v2.1.8 on Fri May 15 2020 11:07:39 GMT+0200 (heure d’été d’Europe centrale)
; Wait for set temperatures to be reached
M116 P0

